package ahpfbhknxzgojyggofxj;

/* loaded from: classes.dex */
public enum rvhplcmttaqkggggovhx {
    FALSE_POSITIVE_REPORTING,
    CANCEL_FALSE_POSITIVE_REPORTING,
    CONFIRMED_FRAUD_REPORTING,
    UNDO_FRAUD_REPORTING,
    SUSPICIOUS_REPORTING,
    UNDO_SUSPICIOUS_REPORTING,
    WHITE_LISTING_REPORTING,
    UNDO_WHITE_LISTING_REPORTING,
    HIGH_ROLLER_REQUEST,
    UNDO_REPORTING,
    SAFE_REPORTING
}
