package ebpswaqugdaofldkaqte;

/* loaded from: classes6.dex */
public enum vubdyxzvpnvcymakzopn {
    PURCHASE,
    MONEY_TRANSFER,
    DEPOSIT,
    WITHDRAW,
    EXTERNAL_DEPOSIT,
    EXTERNAL_MONEY_TRANSFER,
    INTERNATIONAL_MONEY_TRANSFER,
    DEBIT_CARD,
    CREDIT_CARD,
    GIFT_CARD,
    SAVING_DEPOSIT,
    SAVING_WITHDRAW,
    BILL_PAYMENT,
    GOOGLE_PLAY,
    APPLE_PAY,
    QR_PAYMENT,
    POS_CARD_TRANSACTION,
    ATM_WITHDRAW,
    ATM_INSTANT_WITHDRAW,
    ATM_BALANCE,
    CARD_PURCHASE_ONLINE,
    CARD_PURCHASE,
    TOPUP,
    INSTANT_MONEY_TRANSFER,
    DEBIN_MONEY_TRANSFER,
    PAYPAL_DEPOSIT,
    PAYPAL_MONEY_TRANSFER
}
