package hbmifujbkwcjpgteyixs;

/* loaded from: classes6.dex */
public enum lbtmiwirddgqkunoyrov {
    READ_PHONE_STATE,
    READ_EXTERNAL_STORAGE,
    READ_CONTACTS,
    READ_CONTACTS_LIMITED,
    WRITE_EXTERNAL_STORAGE,
    ACCESS_FINE_LOCATION,
    ACCESS_COARSE_LOCATION,
    READ_CALL_LOG,
    BLUETOOTH,
    READ_MEDIA_IMAGES,
    READ_MEDIA_VIDEO,
    PHOTO,
    PHOTO_LIMITED,
    WRITE_SECURE_SETTINGS,
    ACCESS_WIFI_STATE,
    GET_ACCOUNTS,
    CAMERA,
    AUTHORIZED_ALWAYS,
    AUTHORIZED_WHEN_IN_USE,
    REMINDER,
    CALENDAR,
    IDFA
}
